- build.gradle
- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/PopularSortController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/DisableSwaggerSecurity.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> feat : swagger 설정

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/controller/FavoriteController.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewRequest.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
> Feat : Auth, Review, Favorite, User API Swagger 설정  

- src/main/java/com/clubber/ClubberServer/domain/user/exception/UserErrorCode.java
- src/main/java/com/clubber/ClubberServer/global/config/security/AccessDeniedFilter.java
- src/main/java/com/clubber/ClubberServer/global/config/security/FilterConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/security/JwtExceptionFilter.java
> feat :  filter에서 발생한 예외 처리

- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewRequest.java
- src/main/java/com/clubber/ClubberServer/global/dto/ErrorResponse.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalExceptionHandler.java
> feat : spring mvc 에러 처리

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewRequest.java
>  feat : 리뷰 작성 시 유효성 검사 

- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 존재 하지 않는 동아리 예외 적용 

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
> refactor: club 필드에 imageurl 추가 (#85)

- .idea/misc.xml
- src/main/java/com/clubber/ClubberServer/domain/club/dto/OneClubDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/SimpleCenterDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : imageurl 관련 api 수정

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/PopularSortController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
> feat:  swagger 설정

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
- src/main/java/com/clubber/ClubberServer/global/config/security/JwtTokenFilter.java
> feat : JWT 응답 cookie 설정

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
> feat : 토큰 재발급 시 Cookie 적용

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
> refactor : swagger 설정

- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> feat : Cookie 인증 추가 

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
> fix : 토큰 재발급, 로그인 회원가입 swagger 인증 풀기 (#74)

- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> refactor : notice url 변경

- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
> refactor : jquery수정 (#99)

- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
> refactor: error로 인한 주석처리 (#99)

- .idea/misc.xml
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubIdNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/DepartmentNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/DivisionNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/HashtagNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : 쿼리 수정

- src/main/java/com/clubber/ClubberServer/global/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/clubber/ClubberServer/global/config/security/FilterConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalErrorCode.java
> feat : spring security 403 에러 핸들링

- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> bug : same-site, secure 주석 처리 

- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
> fix : 수정된 클래스명 삭제 (#109)

- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/SearchClubDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/SearchClubsDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : 문자열 검색 api

- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : 문자열 검색 api  - upper 적용 + orderby 단순화

- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/HashtagClubDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/HashtagClubsDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/SearchClubsDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : hashtag api 수정

- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteRepository.java
> fix : 메소드 명 변경 

- src/main/java/com/clubber/ClubberServer/domain/club/dto/HashtagClubDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor: hashtag api 반환 json 수정 (#112)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> feat: totalview 증가 로직 구현

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> feat : totalview증가 로직 구현

- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteRepository.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
> fix : 즐겨찾기 추가 시 로직 오류 수정 

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Keyword.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewCreateResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewRequest.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewEnumNotMatchedException.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 리뷰 작성 DTO 변경 

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- build.gradle
> Feat/#129 feat sonarcube 설정 test

- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubIdNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/DepartmentNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/DivisionNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/HashtagNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/exception/ClubAlreadyRegisterdFavoriteException.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/exception/FavoriteAlreadyDeleteException.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/exception/FavoriteNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/exception/FavoriteNotMatchClubException.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/exception/FavoriteNotMatchUserException.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/UserAlreadyReviewedException.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/InvalidTokenException.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/RefreshTokenExpiredException.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/TokenExpiredException.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/UserAlreadyDeletedException.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/UserNotFoundException.java
> Refactor : custom exception 싱글톤 구현 수정

- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/FavoriteResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ClubReviewKeywordStatsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ClubReviewResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/KeywordStats.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ReviewCreateResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/UserReviewResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserFavoritesResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserProfileResponse.java
> refactor : response dto 불변성 접근제어자 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserFavoritesResponse.java
> feat : 나의 즐겨찾기 response에 imageurl 반환 추가

- build.gradle
> feat : logging 의존성 추가 

- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> fix : cookie secure false 처리 (#107)

- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> fix : 옵션 다르게 설정 (#107)

- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperType.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperVO.java
> refactor : enum 데이터 구성 구현 (enummapperType, ennummappervalue) 

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Keyword.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumConfig.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapper.java
> refactor enum 데이터 구성 구현 (enummapper)

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Keyword.java
> Refactor/#149 refactor enum 데이터 구성 구현

- src/main/java/com/clubber/ClubberServer/domain/review/domain/ReviewKeyword.java
> fix : Enum type VARCHAR로 저장 안되는 문제 해결 

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapper.java
> Refactor : 49 refactor enum 데이터 구성 구현 (mapperVO 변환 메서드) 

- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapper.java
> fix : EnumMapper toEnumValues 파라미터 범위 수정 

- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/AccountRole.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/AccountState.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/SnsType.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/User.java
- src/main/java/com/clubber/ClubberServer/domain/user/repository/UserRepository.java
> refactor : 회원user관련 enum 리팩토링

- build.gradle
- src/main/java/com/clubber/ClubberServer/domain/image/controller/ImageController.java
- src/main/java/com/clubber/ClubberServer/domain/image/dto/CreateImagePresignedUrlResponse.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/s3/ImageFileExtension.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/s3/S3Config.java
> feat : s3 presigned url 적용

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/AccountRole.java
> feat : Admin (동아리 관리자) entity 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 동아리 계정 인증 관련 api 구현

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/ReviewKeyword.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ClubReviewsWithContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 리뷰 작성 및 조회 한줄평 적용

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
> bug: 관리자 개별 페이지 수정 api PR 재 upload (#181)

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/UserReviewResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/UserReviewsNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> refactor : 내가 쓴 리뷰 api 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsReviewByStatusResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> refactor : 관리자 - 승인 상태에 따른 리뷰 작성일자 포함+ 최신 날짜 순으로 정렬

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsFirstPageResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- [ x ] 관리자 마이 페이지 클릭시, 동아리 개별 페이지 정보 반환해주는 api 구현
> feat: 관리자 마이 페이지 첫화면 api 구현 (#187)

- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/UserReviewResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
> refactor : 리뷰 반환 시 최신순으로 정렬 반환 구현 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserFavoritesResponse.java
> refactor : clubType enum 적용 (#190)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsReviewByStatusResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsReviewsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsReviewApprovedStatusResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
> Feat : 193 feat 동아리 계정 리뷰 목록 조회

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
> refactor : 동아리 리뷰 관련 api url 분리 및 수정

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsReviewApprovedStatusResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsReviewStatusRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
> refactor : 관리자 리뷰 체크하여 여러개 한꺼번에 승인 미승인 처리

- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> Bug/#202 securityconfig 경로 설정 오류

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> refactor : 카카오 redirect url 구분

- src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
> refactor : 불필요한 cors 허용 origin 삭제 (#143)

- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteCustomRepositoryImpl.java
> refactor : 나의 즐겨찾기 최신순으로 수정 (#212)

- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
- src/main/java/com/clubber/ClubberServer/domain/notice/exception/NoticeErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/notice/exception/NoticeNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/notice/service/NoticeService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat: 개별 공지사항 세부 조회 api 구현

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
> fix : @pathvariable 추가 (#217)

- build.gradle
- src/main/java/com/clubber/ClubberServer/domain/common/controller/ExceptionController.java
- src/main/java/com/clubber/ClubberServer/domain/common/service/ExceptionService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 에러메시지 통합해서 반환하는 api 구현

- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> bug : 배포 서버에서 cookie 적용 안되는 상황

- src/main/java/com/clubber/ClubberServer/domain/faq/controller/FaqController.java
- src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
- src/main/java/com/clubber/ClubberServer/domain/faq/dto/GetFaqsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/faq/service/FaqService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : faq 자주 하는 질문 api

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumConfig.java
> feat : hashtag keyword 목록 반환 api

- src/main/java/com/clubber/ClubberServer/domain/review/controller/KeywordController.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : keyword 목록 반환 api

- src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
> refactor : set - cookie 헤더 allow-access-expose-headers 해제 테스트 (#107)

- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
> fix : 테이블 명 오류 수정 (#234)

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : review - reviewkeyword cascade 적용

- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/User.java
> refactor : 일반 회원 탈퇴 시 즐겨찾기 삭제

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminAlreadyDeletedException.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminRepository.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubAlreadyDeletedException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/faq/controller/FaqController.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> feat : 관리자 회원 탈퇴 api 구현

- src/main/java/com/clubber/ClubberServer/domain/image/controller/ImageController.java
- src/main/java/com/clubber/ClubberServer/domain/image/dto/CreateRecruitsImagePresigneUrlRequest.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
> feat : 모집글 등록 이미지 presigned url api 구현

- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/GetFavoriteDetailsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
- src/main/java/com/clubber/ClubberServer/global/page/PageResponse.java
> feat : 나의 즐겨찾기 pagination

- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/GetFavoriteDetailsResponse.java
> fix : clubtype 추가 (#232)

- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
- src/main/java/com/clubber/ClubberServer/domain/notice/domain/Notice.java
- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticesAtMainResponse.java
- src/main/java/com/clubber/ClubberServer/domain/notice/repository/NoticeRepository.java
- src/main/java/com/clubber/ClubberServer/domain/notice/service/NoticeService.java
> refactor : 공지사항 페이징 처리(#247)

- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
> feat : 나의 즐겨찾기 Pageable @ParameterObject 추가 

- src/main/java/com/clubber/ClubberServer/global/page/PageResponse.java
> refactor : 페이징 처리 시작 페이지 1부터 적용 

- src/main/java/com/clubber/ClubberServer/domain/notice/domain/Notice.java
- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/notice/service/NoticeService.java
> fix : GetNoticeResponse에 totalView추가 (#247)

- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> fix : url 수정 적용 (#244)

- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> fix : url 수정 (#244)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> feat : 동아리 계정 쿠키 적용 

- src/main/resources/logback-spring.xml
> feat : logback 기본 설정 

- .github/workflows/deploy.yml
> fix : logback-spring.xml 적용으로 인한 스크립트 수정 

- src/main/resources/logback-spring.xml
> refactor : log 파일 경로 변수 적용하여 수정 

- src/main/resources/logback-spring.xml
> fix : 경로 수정 

- src/main/resources/logback-spring.xml
> refactor : 경로 수정 

- .github/workflows/ci-main.yml
- Dockerfile
> feat : 운영 서버용 배포 스크립트 작성 (#267)

- .github/workflows/ci-main.yml
> fix : gradle 권한 추가

- .github/workflows/ci-main.yml
> fix : 스크립트 수정

- src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
> feat : faq 예시 데이터 추가 (#228)

- .idea/misc.xml
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
[에러]
2024-08-24 05:02:27.729 [http-nio-8080-exec-7] ERROR
[[dispatcherServlet]:175] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: setFirstResult() or setMaxResults() specified with collection fetch join (in-memory pagination was about to be applied, but 'hibernate.query.fail_on_pagination_over_collection_fetch' is enabled)] with root cause 
org.hibernate.HibernateException: setFirstResult() or setMaxResults() specified with collection fetch join (in-memory pagination was about to be applied, but 'hibernate.query.fail_on_pagination_over_collection_fetch' is enabled)
> refactor : fetch join 제거 & batchsize 추가 [모집글api] (#275)

- .github/workflows/ci-main.yml
- .idea/misc.xml
- Dockerfile
- docker-compose.yml
- src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
> nginx 포함 배포 

- .github/workflows/ci-main.yml
- docker-compose.yml
> fix : 스크립트 수정 

- docker-compose.yml
> fix : 경로 수정

- docker-compose.yml
> fix : 경로수정

- src/main/java/com/clubber/ClubberServer/global/config/security/FilterConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalErrorCode.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalExceptionHandler.java
> refactor : securityconfig filter 구성 수정

- src/main/java/com/clubber/ClubberServer/global/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalErrorCode.java
> refactor : authenticationentrypoint 상태 코드 401로 변경 (#273)

- src/main/resources/logback-spring.xml
> refactor : logback 상대 경로 적용 (#261)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsReviewsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ClubReviewsWithContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 동아리 별 리뷰 paging 처리

- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
> refactor : 동아리 별 리뷰 paging 처리 index 적용 

- .github/workflows/ci-main.yml
- .github/workflows/deploy.yml
> feat : Gradle Caching 스크립트 추가 (#289)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : increaseTotalview메서드 도메인에 정의 (#291)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
> refactor : fetch join 적용 (#293)

- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/ApprovedStatus.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/User.java
> feat : 관리자 회원 탈퇴 시 관련 동아리 리뷰, 즐겨찾기 비활성화 

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
> feat : Hashtag 항목 추가 및 수정 (#225)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
> refactor : 해시태그 목록 수정 및 추가 (#225)

- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapper.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperTypeConverter.java
> Bug :  jpa entity 내 enumerated column이 null 일 경우 에러 해결

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/GetFavoriteDetailsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserFavoritesResponse.java
> fix : Clubtype 반환 시 title 반환하게 수정 (#306)

- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> Bug/#310 bug 리뷰 키워드는 리뷰의 승인 상태와 상관없이 반환되지 않는 문제

- .idea/misc.xml
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/GetFavoriteDetailsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/UserFavoritesResponse.java
> refactor : 검색시 center+small 다르게 나가도록 수정 (#303)

- .idea/misc.xml
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/College.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Department.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Division.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : refactor enum null처리

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/RecruitType.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperType.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperVO.java
> refactor : enummappertype에 이미지 반환 메서드 추가

- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : center,small,etc 한글로+순서 보장(#316)

- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : hashtag- 중앙동아리,소모임,그외 구분해서 나가는 것 수정(#319)

- src/main/java/com/clubber/ClubberServer/domain/image/controller/ImageController.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
> refactor : s3 presignedurl 이미지 처리 변경

- src/main/java/com/clubber/ClubberServer/global/error/GlobalExceptionHandler.java
> feat : 500 에러 로깅

- src/main/java/com/clubber/ClubberServer/domain/review/domain/ReviewKeyword.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 리뷰 validation 처리

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubNotAgreeToProvideInfoException.java
- src/main/java/com/clubber/ClubberServer/domain/club/exception/ClubNotAgreeToProvideReviewException.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> feat : 정보제공 + 리뷰제공 동의 컬럼 추가 + 예외 처리 추가 (#295)

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Keyword.java
> refactor : 리뷰 키워드 이모티콘 추가 (#330)

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsReviewsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/ReviewKeyword.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/ClubReviewsWithContentDetailResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/UserReviewResponse.java
> refactor : 리뷰 키워드 반환 값 변경

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateClubReviewsWithContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewsKeywordStatsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewsWithPageContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewsWithSliceContentResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetUserReviewsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/GetUserFavoritesResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/GetUsersProfileResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
> refactor : 검증 함수 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/global/enummapper/EnumMapperTypeConverter.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalErrorCode.java
- src/main/java/com/clubber/ClubberServer/global/error/GlobalExceptionHandler.java
- src/main/java/com/clubber/ClubberServer/global/exception/EnumTypeNotValidException.java
> refactor : enummappertype 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
> refactor : hashtag not null 추가 (#340)

- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewsKeywordStatsResponse.java
> refactor : 동아리 별 통계 API 리뷰 키워드 반환 타입 변경

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminPendingReviewsWithSliceResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 페이징 처리 방식 변경 (no offset) 승인 대기 리뷰 조회 API 

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
> fix : lastreviewid 필수로 받지 않게 수정 

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
> fix : 순서 수정 (#348)

- build.gradle
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
> refactor : 모집글, 동아리 정보 글자 수 수정

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
> refactor : 리뷰 빈 값 검증 시 stringutils 이용하여 검증

- docker-compose.yml
> feat : cerbot 설정 추가 (#357)

- docker-compose.yml
> fix : yml 수정 (#357)

- docker-compose.yml
> fix : 오타 수정 (#357)

- docker-compose.yml
> fix : 이미지 수정 (#357)

- docker-compose.yml
> Feat/#357 feat cerbot docker compose 적용

- docker-compose.yml
> fix : 경로 수정 (#357)

- docker-compose.yml
> test : 주석 처리 (#357)

- docker-compose.yml
> refactor : 주석 해제 (#357)

- .github/workflows/ci-main.yml
> Feat : dev에서 pull 받은거 빌드 안되어 배포되는 문제 해결 (#370)

- docker-compose.yml
> fix : docker-compose 파일 수정 (#372)

- docker-compose.yml
> fix : 주석 제거 (#372)

- docker-compose.yml
> fix : lastest제거 (#372)

- .github/workflows/ci-main.yml
> fix : cicd-main.yml원상복구 (#372)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
- src/main/java/com/clubber/ClubberServer/global/vo/ImageVO.java
> refactor : 이미지 서버 url 적용

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewAgreedStatusResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> feat : 동아리 리뷰 동의 여부 반환 api 구현

- docker-compose.yml
> fix : 이미지명 수정 (#382)

- .github/workflows/ci-main.yml
> refactor : 프런트 이미지 추가 (#382)

- docker-compose.yml
> fix : docker-compose 수정 (#382)

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubIntoCardResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/dto/GetFavoriteDetailsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/GetUserFavoritesResponse.java
- src/main/java/com/clubber/ClubberServer/global/vo/ImageVO.java
> refactor : imagevo 적용

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> Bug/#390 카카오 로그인 redirect url 수정

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/PopularController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/faq/controller/FaqController.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/controller/FavoriteController.java
- src/main/java/com/clubber/ClubberServer/domain/image/controller/ImageController.java
- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/adminRecruitController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/KeywordController.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
> refactor : /api prefix 전체 추가 (#393)

- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
> refactor : cookie secure 옵션 적용 (#397)

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
> fix : Origin header대신 referer 헤더 사용하여 분기 (#402)

- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> fix : redirect uri 수정 (#402)

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
> chore : log 추가 (#402)

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> redirect url 로그 추가 

- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> refactor : 카카오 redirect url 개발 서버 서브 도메일 적용 (#402)

- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
> fix : 분기 기준 변경 (#402)

- .github/workflows/ci-dev.yml
- .github/workflows/deploy.yml
- docker-compose.yml
> Refactor/#412 refactor 개발 서버 배포 방식 통일

- src/main/java/com/clubber/ClubberServer/global/jwt/JwtStatic.java
> fix : redirect url 수정 (#412)

- .github/workflows/ci-cd-dev.yml
- docker-compose.yml
> Refactor/#412 refactor 개발 서버 배포 방식 통일 : 기타 수정 

- .github/workflows/ci-cd-dev.yml
> fix : 오타 수정 (#412)

- docker-compose.yml
> fix : 이미지 명 수정 (#412)

- .github/workflows/ci-cd-dev.yml
> refactor : docker 작업 통합 (#412)

- src/main/java/com/clubber/ClubberServer/domain/image/dto/CreateImagePresignedUrlResponse.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
> Bug/#428 개발 서버 이미지 url 오류 수정

- src/main/java/com/clubber/ClubberServer/domain/notice/controller/NoticeController.java
> fix : 개별 공지사항 url - v1 중복 제거 (#430)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
> refactor : etc enum ETC 수정 (#423)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
> refactor : 모집글 title length 지정 (#418)

- src/main/java/com/clubber/ClubberServer/domain/notice/domain/Notice.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/RecruitImage.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : 모집글, 공지사항 ImageVO 적용 (#431)

- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
> fix : 개별 공지사항 조회 시 imagevo 누락 추가 (#431)

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : hashtag 목록 ETC 포함 전체 반환 (#438)

- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
> fix : 홍보 게시판 개별 모집글 조회 url - v1 중복 제거 (#437)

- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminEqualsPreviousPasswordExcpetion.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
> Refactor/#441 refactor 관리자 이전 비밀번호로 변경 시 예외 발생 

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/image/dto/CreateImagePresignedUrlResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> Refactor/#444 refactor 이미지 관련 변수명 수정

- src/main/java/com/clubber/ClubberServer/domain/notice/domain/Notice.java
- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
> refactor : imageUrl, imageUrls로 변경 (#446)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : 모집글 post api 수정 (#446)

- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> refactor : swagger config url 설정 주입 방식 면경 (#449)

- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> refactor : 기존 swagger 설정 주석 삭제 (#449)

- src/main/java/com/clubber/ClubberServer/global/infrastructure/s3/ImageFileExtension.java
> fix : JPG 요청값 jpeg로 수정 (#452)

- .github/workflows/ci-cd-dev.yml
> refactor : 개발 서버 이미지 분리 (#454)

- docker-compose.yml
> refactor : docker compose 수정 (#454)

- .github/workflows/ci-cd-dev.yml
- .github/workflows/ci-cd-prod.yml
- .github/workflows/ci-cd.yml
> 통합 스크립트 작성 시도 

- .github/workflows/ci-cd.yml
> fix : 스크립트 수정 (#454)

- .github/workflows/ci-cd.yml
- Dockerfile.dev
- Dockerfile.prod
> refactor : Dockerfile 환경별 분리 적용 (#454)

- docker-compose-dev.yml
> feat : log volume 설정 추가 (#464)

- docker-compose-prod.yml
> feat : 운영 서버 로그 볼륨 설정 (#464)

- docker-compose-dev.yml
> refactor : 3000포트 설정 변경 (#467)

- docker-compose-dev.yml
- docker-compose-prod.yml
> Refactor/#467 refactor 외부 포트 접속 설정 리팩토링

- docker-compose-prod.yml
> refactor : 운영 서버 3000포트 EXPOSE로 변경 (#467)

- src/main/java/com/clubber/ClubberServer/ClubberServerApplication.java
- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/helper/CookieHelper.java
- src/main/java/com/clubber/ClubberServer/global/helper/SpringEnvironmentHelper.java
> refactor : 운영 환경에 따른 쿠키 설정 변경

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/User.java
- src/test/java/com/clubber/ClubberServer/review/ReviewServiceTest.java
- src/test/java/com/clubber/ClubberServer/review/controller/ReviewControllerTest.java
- src/test/java/com/clubber/ClubberServer/review/service/ReviewServiceTest.java
- src/test/java/com/clubber/ClubberServer/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/util/WithMockCustomUser.java
- src/test/java/com/clubber/ClubberServer/util/fixture/ReviewFixture.java
> test : 리뷰 작성 테스트 코드 

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/test/java/com/clubber/ClubberServer/admin/service/AdminServiceTest.java
- src/test/java/com/clubber/ClubberServer/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/util/fixture/AdminFixture.java
> Bug/#482 bug 동아리 정보 수정 api 이미지 수정 안하고 요청 시 예외처리 안되는 문제

- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/global/image/ImageUtil.java
- src/test/java/com/clubber/ClubberServer/admin/service/AdminServiceTest.java
- src/test/java/com/clubber/ClubberServer/global/image/ImageUtilTest.java
> feat : 이미지 키 파싱 유틸 기능 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/test/java/com/clubber/ClubberServer/admin/controller/AdminControllerTest.java
- src/test/java/com/clubber/ClubberServer/util/fixture/AdminFixture.java
> Refactor/#488 feat 동아리 소개 글자수 validation 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsReviewStatusRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
- src/test/java/com/clubber/ClubberServer/admin/controller/AdminReviewControllerTest.java
- src/test/java/com/clubber/ClubberServer/admin/service/AdminReviewServiceTest.java
- src/test/java/com/clubber/ClubberServer/util/fixture/AdminReviewFixture.java
> refactor : 리뷰 승인 / 거절 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/review/dto/GetClubReviewsKeywordStatsResponse.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/KeywordStat.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/KeywordStats.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
> refactor : 동아리 리뷰 통계 서비스 리팩토링

- src/main/java/com/clubber/ClubberServer/domain/review/domain/Keyword.java
- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/global/validator/Enum.java
- src/main/java/com/clubber/ClubberServer/global/validator/EnumValidator.java
> feat : enum validator 구현

- src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateReviewClubWithContentRequest.java
- src/main/java/com/clubber/ClubberServer/global/validator/unique/Unique.java
- src/main/java/com/clubber/ClubberServer/global/validator/unique/UniqueConstraintValidator.java
> feat : 리뷰 키워드 unique validator 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
- src/test/java/com/clubber/ClubberServer/admin/service/AdminServiceTest.java
- src/test/java/com/clubber/ClubberServer/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/util/fixture/ReviewFixture.java
> refactor : 동아리 관리자 회원 탈퇴 시 모집글 삭제 로직 추가

- src/main/java/com/clubber/ClubberServer/domain/auth/component/UserWithdraw.java
- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/domain/user/domain/User.java
> fix : 회원 탈퇴 시 401 에러 

- build.gradle
- docker-compose-dev.yml
- docker-compose-local.yml
- prometheus.yml
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 프로메테우스 테스트 

- docker-compose-dev.yml
> fix : 프로메테우스 볼륨 경로 수정 (#514)

- .github/workflows/ci-cd.yml
- docker-compose-dev.yml
> fix : prometheus.yml 파일 이동 배포 스크립트에 포함 (#514)

- prometheus.yml
> fix : ip 주소로 수정 (#514)

- prometheus.yml
> fix : target 수정 (#514)

- docker-compose-dev.yml
> feat : grafana 컨테이너 추가

- docker-compose-dev.yml
> refactor : grafana 포트 설정 (#514)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
> refactor : 인덱스 방향 변경 (#526)

- src/main/java/com/clubber/ClubberServer/domain/example/ExampleController.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/ApiErrorCodeExample.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/ExampleHolder.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> feat :  도메인 별 에러케이스 swagger 통해 반환

- docker-compose-prod.yml
> deploy : compose-prod 파일 수정

- docker-compose-prod.yml
> docker-compose-prod수정

- src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/user/exception/UserErrorCode.java
> fix : 상태 코드 오류 수정 (#530)

- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : 삭제된 모집글 필터링 되도록 코드 수정 (#511)

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : transctional annotation 추가 (#533)

- docker-compose-dev.yml
- docker-compose-prod.yml
> feat : docker-compose timezone 설정

- docker-compose-dev.yml
> refactor : docker-compose-dev entrypoint 수정 (#547)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
* SRP 를 준수하지 않는 것같아, DTO에서 저렇게 처리하는게 맞는건지 고민..
> feat : clubType dto에 추가 (#550)

- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> feat : 모집글 content 앞부분만 반환 (#552)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
>  refactor : Recruit entity 필드 초기화, 생성자 매개변수 제거 (#554)

- .github/workflows/ci-cd.yml
- Dockerfile.nginx.dev
- docker-compose-dev.yml
> feat : geoip 관련 설정 (#549)

- Dockerfile.nginx.dev
> fix : 모듈 경로 재성절 (#549)

- Dockerfile.dev
> fix : 빌드 시 컨테이너 curl 설치 (#567)

- .github/workflows/ci-cd.yml
> refactor : github secret 통합 

- .github/workflows/ci-cd.yml
> refactor : key 수정 (#567)

- .github/workflows/ci-cd.yml
> fix : prometheus 복사 삭제 (#567)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetOneRecruitMainPageResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetRecruitsMainPageResponse.java
> Refactor : response dto - final, @Schema 추가 + 유효성 검증 추가(#566)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
> refactor : Recruit request dto - @NotNull 어노테이션 제거 (#579)

- src/main/java/com/clubber/ClubberServer/domain/club/dto/CollegeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/DepartmentSmallDto.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByDivisionResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubInfoResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubIntoCardResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubPopularResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsByHashTagResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchResponse.java
> refactor : club dto 에 final + schema 추가 (#581)

- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticesAtMainResponse.java
- src/main/java/com/clubber/ClubberServer/domain/notice/mapper/NoticeMapper.java
- src/main/java/com/clubber/ClubberServer/domain/notice/service/NoticeService.java
- src/main/java/com/clubber/ClubberServer/domain/owner/domain/Owner.java
> refactor : notice dto (final, schema 추가) + mapper 구현 (#585)

- .github/workflows/ci-cd.yml
- Dockerfile.nginx.prod
- docker-compose-prod.yml
> feat : cicd, docker-compose, dockerfile 생성 및 수정 (#589)

- docker-compose-prod.yml
> feat: 마운트 문제로 주석처리 (#589)

- docker-compose-prod.yml
> dev -> main

- docker-compose-prod.yml
> feat: volume 주석 해제 (#589)

- .github/workflows/ci-cd.yml
> feat : 재배포위해 수정

- build.gradle
- src/main/java/com/clubber/ClubberServer/global/config/async/AsyncConfig.java
- src/main/java/com/clubber/ClubberServer/global/config/mail/MailConfig.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
- src/main/java/com/clubber/ClubberServer/global/properties/MailProperties.java
> feat : 메일 전송 서비스 구현 (591) 

- src/main/java/com/clubber/ClubberServer/domain/review/dto/KeywordCountStatDto.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/vo/KeywordStatsVO.java
> bug : 리뷰 키워드 통계 오류 수정 

- src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/CreateTextAnalyzeRequest.java
> refactor : 동아리 별 리뷰 조회시 승인 상태 제외

- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
- src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
- src/main/java/com/clubber/ClubberServer/domain/auth/facade/UserRegisterFacade.java
- src/main/java/com/clubber/ClubberServer/domain/auth/facade/UserWithdrawFacade.java
- src/main/java/com/clubber/ClubberServer/global/common/consts/ClubberStatic.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEvent.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventHandler.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventPublisher.java
> refactor : 회원 탈퇴 시 soft delete 비동기 적용

- docker-compose-dev.yml
- src/main/resources/logback-spring.xml
> feat : loki promtail 개발 서버 연동 테스트 

- docker-compose-dev.yml
> refactor : 제어 문자 허용 (#622)

- docker-compose-dev.yml
> refactor : network 추가 (#622)

- docker-compose-dev.yml
> feat : log파일 promtail container과 볼륨 처리 (#622)

- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : 모집글 - 유지되는 이미지 ordernum 증가 로직 누락된 것 추가 (#628)

- docker-compose-dev.yml
> prometheus gateway 연결 

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetSummaryClubGroupResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetSummaryClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> feat : 분과 포함 + 분과 별로 그룹핑하여 보내는 걸로 수정 (#586)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/adminRecruitController.java
- src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
> feat : 스웨거 api 그룹화 (#640)

- src/main/resources/console-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/logback-spring.xml
> refactor : 운영 환경 별 로그 출력 수정 변경 (#631)

- docker-compose-prod.yml
> refactor : docker compose prod 수정 (#631)

- Dockerfile.nginx.dev
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminServiceTest.java
> refactor : 멀티 빌드 스테이지 적용 (#647)

- Dockerfile.nginx.dev
> refactor : 실행시 필요한 라이브러리는 유지하도록 수정 (#647)

- Dockerfile.nginx.prod
> refactor : 운영서버 nginx docker file 수정 (#652)

- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/favorite/service/FavoriteServiceTest.java
> refactor : 동아리 즐겨찾기 여부 반환 api 구현

- src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
- src/main/java/com/clubber/ClubberServer/domain/user/dto/GetIsUserFavoriteResponse.java
- src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/favorite/service/FavoriteServiceTest.java
> refactor : 회원의 즐겨찾기 여부 dto로 수정 (#657)

- src/main/resources/logback-spring.xml
> fix : logback 수정 (#657)

- src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
> refactor : 해시태그 - 미디어, 영화 추가 (#666)

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> refactor : Division 분과 저장 순서대로 반환 (#669)

- src/main/java/com/clubber/ClubberServer/domain/review/mapper/ReviewMapper.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/domain/review/vo/KeywordStatsVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumDefaultMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumFaQMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumImageMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumMapperVO.java
- src/test/java/com/clubber/ClubberServer/unit/domain/review/mapper/ReviewMapperTest.java
- src/test/java/com/clubber/ClubberServer/unit/domain/review/vo/ReviewKeywordVOTest.java
Enum -> String으로의 key 변환작업을 VO 내부에서 수행하게 변경 
추후 확장성을 유지하기 위해 EnumMap은 유지하되, String이 key인 Map 변수 추가
> Refactor/#675 : 리뷰 통계 일급 컬렉션 불변성 보장 개선

- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumDefaultMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumFaQMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumImageMapperVO.java
#675
VO 리스트가 바로 직렬화 되어 반환되기 때문에 getter가 필요함
> fix : VO 직렬화 문제 해결 

- docker-compose-prod.yml
> fix : loki 의존 삭제 (#678)

- src/main/resources/file-info-appender.xml
> refactor : 로그 파일명 통일 (#678)

- docker-compose-prod.yml
- src/main/resources/file-info-appender.xml
> dev -> prod 

- src/test/java/com/clubber/ClubberServer/integration/domain/club/controller/ClubControllerTest.java
- src/test/java/com/clubber/ClubberServer/integration/domain/club/service/ClubServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
> test: club 관련 테스트코드 작성 (#643)

- Readme.md
> docs : 기타 개행 수정 (#688)

- Readme.md
> Docs/688 feat docs 수정

- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
> refactor : 공식 단체 이름 변경 (#696)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
- src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitFixture.java
> feat : everytimeUrl 추가 (#695)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
> refactor : 모집글 수정- everytimeurl 업데이트 로직 추가 (#700)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCalendarService.java
> refactor: LocalDateTime으로 변경+ 밀리 초 제거 (#714)

- src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
- src/main/java/com/clubber/ClubberServer/global/config/log/LogInterceptor.java
- src/main/java/com/clubber/ClubberServer/global/config/log/WebConfig.java
#716 
Request Body, Header는 추후 구현
> feat : 인터셉터를 이용한 로깅 구현 

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminClubService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubInfoResponse.java
- src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
> feat : 유튜브링크 추가 (#711)

- src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
- 운영 서버  : 운영 서버 Origin 허용 
- 개발 서버 : 개발 서버 / localhost Origin 허용
> refactor : 운영 환경 별 허용 origin pattern 분리 (#662)

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminSignupAuth.java
> refactor : 엔티티 명 수정(#731)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminInvalidCurrentPasswordException.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAuthService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/validator/AdminValidator.java
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
- src/test/java/com/clubber/ClubberServer/unit/domain/admin/service/AdminAccountServiceTest.java
- src/test/java/com/clubber/ClubberServer/unit/domain/admin/validator/AdminValidatorTest.java
> refactor : 관리자 비밀번호 변경 api 수정

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Contact.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/PendingAdminInfo.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignUpRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignUpResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminsProfileResponse.java
- src/main/java/com/clubber/ClubberServer/global/event/signup/SignUpAlarmEventHandler.java
- src/main/java/com/clubber/ClubberServer/global/event/signup/SignUpAlarmEventPublisher.java
- src/main/java/com/clubber/ClubberServer/global/event/signup/signUpAlarmEvent.java
> refactor : 기타 연락수단 포함 관리자 api 수정

- Readme.md
> docs : 추가 운영 인프라 블로그 글

- src/main/java/com/clubber/ClubberServer/domain/image/controller/ImageController.java
- src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 동아리 관리자 회원 가입 시 증빙 이미지 presigned url 발급 API  (#747)

- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsFindResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchForSignUpResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> feat : 회원가입시 동아리명 검색 api 구현 (#750)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminEmailAuthController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminPasswordFindAuth.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminSignupAuth.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminUsernameFindAuth.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminFindMailAuthRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminPasswordFindRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignupAuthRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignupAuthVerifyRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminUsernameFindAuthRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminUsernameFindRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/GetAdminUsernameFindResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminPasswordFindAuthVerifyRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminUsernameFindAuthVerifyRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateVerifyAdminEmailAuthRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminRepository.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminUsernameFindAuthRepository.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminEmailAuthService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReadService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/util/AdminUtil.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminEmailAuthServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
- src/test/java/com/clubber/ClubberServer/unit/domain/admin/facade/AdminEmailAuthFacadeTest.java
> feat : 동아리 아이디 찾기 api 구현

- src/main/java/com/clubber/ClubberServer/global/config/async/AsyncConfig.java
- src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/async/AsyncExceptionAlaramEvent.java
- src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/async/AsyncExceptionAlaramHandler.java
- src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/async/AsyncExceptionAlarmPublisher.java
- src/main/java/com/clubber/ClubberServer/global/exception/GlobalErrorCode.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/exception/MailNotSentException.java
> 756 : refactor 이메일 전송 비동기 처리

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminSignupAuth.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
> fix : 회원 가입 인증번호 검증 시 인증 여부 변경 추가

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminSignupAuth.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignUpRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminEmailAuthService.java
> refactor : authCode 포함 Request 회원가입시 검증 추가 (#760)

- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminUsernameNotFoundException.java
- src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
> refactor : 비밀번호 찾기 인증번호 전송 시 아이디 존재하지 않는 경우 예외 처리 추가

- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchForSignUpResponse.java
> refactor : club id 포함반환 (#764)

- .github/workflows/ci-cd.yml
- docker-compose-dev.yml
> refactor : FE 이미지 명 변경 반영 (#767)

- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/validator/FavoriteValidator.java
- src/test/java/com/clubber/ClubberServer/integration/domain/favorite/service/FavoriteServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/domain/user/service/UserServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/ClubFixture.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/FavoriteFixture.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/UserFixture.java
- src/test/java/com/clubber/ClubberServer/unit/domain/favorite/domain/FavoriteDomainTest.java
- src/test/java/com/clubber/ClubberServer/unit/domain/favorite/validator/FavoriteValidatorTest.java
> test : favorite 테스트 코드 작성

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/controller/SearchController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchForSignUpResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> feat : clubtype목록 반환 api 구현 + 동아리명 검색 api 수정 (#773)

- src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Contact.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminContactRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminContactResponse.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
> feat : 연락수단 변경 API 

- Readme.md
> docs : 블로그 글 추가 (#743)

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminRepository.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/PendingAdminInfoRepository.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
- src/main/java/com/clubber/ClubberServer/domain/owner/service/OwnerService.java
> Feat/#779 feat 백오피스 회원가입 승인 api 구현

- src/main/java/com/clubber/ClubberServer/domain/admin/repository/PendingAdminInfoRepository.java
- src/main/java/com/clubber/ClubberServer/domain/owner/service/OwnerService.java
- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
> refactor : 인증 메일 html 추가

- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
> refactor : 네이버 메일용 html 수정 (#781)

- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
> refactor :  인증메일 이미지 css 수정 (#781)

- src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
> refactor : 인증 메일 css 수정 (#781)

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/PendingAdminInfo.java
- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignUpRequest.java
- src/main/java/com/clubber/ClubberServer/domain/admin/repository/PendingAdminInfoRepository.java
- src/main/java/com/clubber/ClubberServer/domain/owner/service/OwnerService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
- 프런트에서 소모임 타입 클릭 제외, 단과대, 학과 필드는 ETC로 값 세팅 후 요청
> refactor : 회원가입시 reqeust 단과대 학과 추가

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 소모임 단과대, 학과 조회 api 구현 (#785)

- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
> refactor : 커버링 인덱스 querydsl 기타 수정

- src/main/java/com/clubber/ClubberServer/global/common/logging/ReqResLoggingFilter.java
> fix : 메트릭 정보 로깅 제외 (#792)

- Readme.md
> docs : 블로그 글 수정 (#743)

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/domain/Favorite.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/repository/FavoriteCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/favorite/service/FavoriteService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEvent.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventHandler.java
- src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventPublisher.java
- src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
> refactor : 관리자 탈퇴 후 데이터 삭제 작업 수정 

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
- src/main/java/com/clubber/ClubberServer/domain/club/dto/CollegeResponse.java
- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
- src/main/java/com/clubber/ClubberServer/domain/faq/controller/FaqController.java
- src/main/java/com/clubber/ClubberServer/domain/faq/service/FaqService.java
- src/main/java/com/clubber/ClubberServer/domain/review/controller/KeywordController.java
- src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumDefaultMapperType.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumFaqMapperType.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumImageMapperType.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumMapper.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumMapperType.java
- src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumFaQMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumImageMapperVO.java
- src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumMapperVO.java
> refactor : 마커인터페이스 대신 최상위 VO 클래스를 반환 타입으로 지정 (#800)

- Readme.md
> docs : 글 삭제 (#743)

- src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubCategoryController.java
> refactor : url 네이밍 변경 (#803)

- src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAuthService.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReadService.java
- src/main/java/com/clubber/ClubberServer/global/util/RandomAuthCodeUtil.java
> refactor : admin email facade 재구성

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/RecruitComment.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitCommentAppender.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitCommentReader.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitReader.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitValidator.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/mapper/RecruitMapper.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCommentService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/vo/RecruitCommentVO.java
> refactor : recruit / comment implement 계층 분리

- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/adminRecruitController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/RecruitImage.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitComment/PostRecruitCommentRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitAppender.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitCommentAppender.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitImageAppender.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitReader.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitValidator.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> refactor : recruit Service 로직 implement 분리

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubCategoryService.java
> refactor : 기타 분과 제외하여 리스트 반환 (#821)

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateLinkedCalenderResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
> feat : 연동 캘린더 저장 수정 사항 반영

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/entity/Calendar.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/AdminCalendarService.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
- src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
> feat : 관리자 페이지 캘린더 조회 api 구현

- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitLinkedCalendarService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
feat : 모집글 삭제시 연동된 캘린더도 삭제되도록 수정
> feat : 모집글 삭제시 연동된 캘린더도 삭제되도록 수정 (#843)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
> fix : 생성자에서 기본값 세팅 (#848)

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
> fix : @notnull 제약 추가 (#848)

- docker-compose-dev.yml
docker-compose-dev.yml에도 이미지 변경사항 반영
> chore : docker-compose-dev.yml에도 이미지 변경사항 반영(#852)

- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarDuplicateRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarDuplicateResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/UpdateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/entity/Calendar.java
> refactor : 캘린더 api 기타 수정 

- src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitFixture.java
> test : recruit 테이블 관련 테스트코드 데이터 수정

- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarDuplicateResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarAdminService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/calendar/service/CalendarAdminServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/CalendarFixture.java
> test : 캘린더 중복 조회 통합테스트

- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitLinkedCalendarService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitLinkedCalendarServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/ClubFixture.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitFixture.java
> test : 모집글 저장 이후 연동 캘린더 저장 통합 테스트 코드

- src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
- src/main/java/com/clubber/ClubberServer/domain/admin/domain/PendingAdminInfo.java
- src/main/java/com/clubber/ClubberServer/domain/admin/implement/AdminAppender.java
- src/main/java/com/clubber/ClubberServer/domain/admin/implement/AdminReader.java
- src/main/java/com/clubber/ClubberServer/domain/admin/implement/PendingAdminInfoAppender.java
- src/main/java/com/clubber/ClubberServer/domain/admin/implement/PendingAdminInfoManager.java
- src/main/java/com/clubber/ClubberServer/domain/admin/implement/PendingAdminInfoReader.java
- src/main/java/com/clubber/ClubberServer/domain/admin/mapper/PendingAdminMapper.java
- src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
- src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
- src/main/java/com/clubber/ClubberServer/domain/owner/service/OwnerService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/owner/service/OwnerServiceTest.java
- src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
> refactor : 동아리 회원가입 승인 admin api 수정 

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminSignUpRequest.java
> fix : null일때 기본값 할당 (#864)

- src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
> chore : 3001 추가 (#867)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneAdminRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
> refactor : 관리자 모집글 상태 응답 추가 (#871)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneAdminRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
> Refactor/#871 refactor 모집글 조회시 모집 상태 반환값 추가

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarAdminController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarResponseWithLinkedStatus.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarAdminService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitReader.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
> refactor : calendar 연동된 Recruit 조회 쿼리 수행 (#875)

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarInListResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
> refactor : 캘린더 모집 기간 범위 수정

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarAdminController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarAdminService.java
> feat : 관리자 캘린더 필터링 구현 (#883)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitPeriodNotAllowedException.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/implement/RecruitValidator.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
> fix : 상시모집의 경우 startAt, endAt null 허용되도록 변경

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
> feat : 캘린더 단일 조회 (비로그인, createdAt 추가) (#887)

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetTodayCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
> feat : 오늘 마감일자인 캘린더 조회

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarAdminController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarAdminService.java
> refactor : 캘린더 필터 기준 수정 반영

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetNextAlwaysCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepository.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
> feat : 특정 동아리 상시모집 복수일경우 no offset 팝업 페이지 구현 (#899)

- src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
> chore : ETC 제외 (#904)

- src/main/java/com/clubber/ClubberServer/domain/calendar/domain/Calendar.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
- src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitLinkedCalendarServiceTest.java
> refactor : 모집글 연동 끊기시 url 초기화 (#907)

- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarMapper.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/implement/CalendarReader.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/repository/CalendarCustomRepositoryImpl.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarAdminService.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/service/CalendarService.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/controller/RecruitLinkedCalendarController.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/CreateLinkedCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitLinkedCalendarService.java
- src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitLinkedCalendarServiceTest.java
> refactor : 연동 캘린더 저장시 Mapper 도입 (#911)

- src/main/java/com/clubber/ClubberServer/domain/calendar/controller/CalendarAdminController.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarDuplicateRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarResponseWithLinkedStatus.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetNextAlwaysCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetTodayCalendarResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneAdminRecruitResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
> chore : dto 누락된 validation swagger

- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/GetCalendarDuplicateRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/UpdateCalendarRequest.java
> fix : Enum 타입 validation 수정 (#919)

- src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
- src/main/java/com/clubber/ClubberServer/domain/recruit/mapper/RecruitMapper.java
> refactor : 모집글 preview 삭제 (#926)

- src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
> fix : 동아리 소개글 글자수 제한 수정 (#928)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewKeywordCustomRepositoryImpl.java
- Clubber-External/src/main/java/com/clubber/domain/review/dto/ClubReviewResponse.java
> Refactor/#938 refactor 리뷰 도메인 변경사항 반영

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/exception/ReviewErrorCode.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/exception/ReviewUserNotMatchException.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/implement/ReviewReader.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/implement/ReviewValidator.java
- Clubber-External/src/main/java/com/clubber/domain/review/service/ReviewService.java
- Clubber-External/src/main/java/com/clubber/domain/user/controller/UserController.java
- Clubber-External/src/main/java/com/clubber/domain/user/dto/UserReviewResponse.java
- Clubber-External/src/test/java/com/clubber/ClubberServer/integration/domain/review/service/ReviewServiceTest.java
- Clubber-External/src/test/java/com/clubber/ClubberServer/integration/util/fixture/ReviewFixture.java
> refactor : 회원 관련 리뷰 API 수정 

- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/CreateCalendarRequest.java
- src/main/java/com/clubber/ClubberServer/domain/calendar/dto/UpdateCalendarRequest.java
> fix : 상시일경우 일정 null 허용 (#943)

- Clubber-External/src/main/java/com/clubber/domain/calendar/dto/CreateCalendarRequest.java
- Clubber-External/src/main/java/com/clubber/domain/calendar/dto/UpdateCalendarRequest.java
> fix : null 허용 (#946)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/domain/ReviewSortType.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepository.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
- Clubber-External/src/main/java/com/clubber/domain/admin/controller/AdminReviewController.java
- Clubber-External/src/main/java/com/clubber/domain/admin/service/AdminReviewService.java
- Clubber-External/src/main/java/com/clubber/domain/review/controller/ReviewController.java
- Clubber-External/src/main/java/com/clubber/domain/review/service/ReviewService.java
> feat : 정렬 타입 추가

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/domain/Review.java
- Clubber-External/src/main/java/com/clubber/domain/review/dto/ClubReviewResponse.java
> refactor : 신고된 경우 content null로 반환 (#938)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
> fix : on절로 변경 (#938)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
> fix : 기존 정렬된 tuple 기준으로 다시 정렬 수행 (#938)

- Clubber-External/src/main/java/com/clubber/domain/admin/controller/AdminReviewController.java
> chore : swagger 수정 (#938)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/report/domain/Report.java
Report도메인 id(pk)에 strategy 설정 추가
> refactor : Report도메인 id(pk)에 strategy 설정 추가

- Clubber-Domain/src/main/java/com/clubber/domain/domains/report/repository/ReportRepository.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/domain/Review.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/exception/ReviewErrorCode.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/exception/ReviewHasReportException.java
- Clubber-External/src/main/java/com/clubber/domain/review/dto/UpdateClubReviewContentRequest.java
- Clubber-External/src/main/java/com/clubber/domain/review/service/ReviewService.java
- Clubber-External/src/main/java/com/clubber/domain/user/controller/UserReviewController.java
- Clubber-External/src/main/java/com/clubber/domain/user/dto/UserReviewResponse.java
> feat : 리뷰 수정 api 구현

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/domain/Review.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepository.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
- Clubber-External/src/main/java/com/clubber/domain/review/mapper/ReviewMapper.java
- Clubber-External/src/main/java/com/clubber/domain/review/service/ReviewService.java
- Clubber-External/src/main/java/com/clubber/domain/user/controller/UserReviewController.java
- Clubber-External/src/main/java/com/clubber/domain/user/dto/GetUserReviewReportResponse.java
> feat : 회원 리뷰 다음 신고 목록 조회 (#975)

- Clubber-External/src/main/java/com/clubber/domain/user/controller/UserReviewController.java
> chore : 쿼리 파라미터 선택으로 (#975)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
> fix : fetchjoin 제거 (#975)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
> fix : 쿼리 수정 (#975)

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/repository/ReviewCustomRepositoryImpl.java
- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/vo/ClubReviewResponse.java
> refactor : 동아리별 리뷰에 답글 DTO 추가

- Clubber-Domain/src/main/java/com/clubber/domain/domains/review/vo/KeywordStatsVO.java
> fix : 인자 누락 (#984)
